#!/bin/bash

# If we don't have a file, start at 1.0
if [ ! -f "/tmp/backlight.val" ] ; then
    BRIGHTNESS=1.0
else
    BRIGHTNESS=`cat /tmp/backlight.val`
fi

# If we have a running instance, let's get ready to kill it
if [ -f "/tmp/backlight.pid" ] ; then
    TOKILL=`cat /tmp/backlight.pid`
fi

if [ -z "$TOKILL" ];
then echo "No running instance of redshift detected" 
else
kill -9 "$TOKILL"
redshift -x;
fi 

while getopts "b:id" option
do
case "${option}"
in
b) BRIGHTNESS=${OPTARG};;
i) BRIGHTNESS=$(echo "${BRIGHTNESS} + 0.1" | bc -l);;
d) BRIGHTNESS=$(echo "${BRIGHTNESS} - 0.1" | bc -l);;
esac
done

if [ "${BRIGHTNESS}" = "0" ]; then
    BRIGHTNESS=0.1;
fi
if [ "${BRIGHTNESS}" = "1.1" ]; then
    BRIGHTNESS=1;
fi

# Let's store the brightness for later use
echo "${BRIGHTNESS}" > /tmp/backlight.val

# Let's run our instance of redshift
redshift -b ${BRIGHTNESS} > /dev/null &> /dev/null &
REDSHIFT_PID=$!

# Now storing the new pid
echo "${REDSHIFT_PID}" > /tmp/backlight.pid
