#!/bin/bash

# If we don't have a file, start at 1.0
if [ ! -f "/tmp/backlight.val" ] ; then
    BRIGHTNESS=1.0
else
    BRIGHTNESS=`cat /tmp/backlight.val`
fi

while getopts "b:id" option
do
case "${option}"
in
b) BRIGHTNESS=${OPTARG};;
i) BRIGHTNESS=$(echo "${BRIGHTNESS} + 0.1" | bc -l);;
d) BRIGHTNESS=$(echo "${BRIGHTNESS} - 0.1" | bc -l);;
esac
done

if [ "${BRIGHTNESS}" = "0" ]; then
    BRIGHTNESS=0.1;
fi
if [ "${BRIGHTNESS}" = "1.1" ]; then
    BRIGHTNESS=1;
fi

# Let's run our instance of redshift
redshift -P -o -b ${BRIGHTNESS} > /dev/null &> /dev/null &
