#!/usr/bin/python

import subprocess
import sys

updateCount = subprocess.Popen("checkupdates | wc -l", shell=True, stdout=subprocess.PIPE).stdout.readline()

if str(updateCount)[2] == '0': 
    print("")
else:
    sys.stdout.buffer.write(updateCount)

