#!/bin/sh

# You can call this from *within* vi!

# Usage:
# <command> | ix # -> uploads to ix
# ix <id> -> ouputs ix link

if [ -n "$1" ]; then
  exec curl -s "ix.io/$1"
  exit 0
fi

url=$(curl -s -F 'f:1=<-' http://ix.io)
# wee "$url" 2>/dev/null
echo "$url"
which xclip >/dev/null || exit 0
echo "$url" | xclip 
