#!/usr/bin/python

import imaplib

try:

    gpassFile = open("")
    gmail = imaplib.IMAP4_SSL('imap.gmail.com',993)
    gmail.login('',gpassFile.read())
    gmail.select()

    val = 0;
    val = len(gmail.search(None, 'UnSeen')[1][0].split());
    if val != 0 :
        print(val)
    else :
        print("")
except:
    print("")
