#!/usr/bin/python

import imaplib

try:

    gpassFile = open("private/mailCount_gmailPassword")
    gmail = imaplib.IMAP4_SSL('imap.gmail.com',993)
    gmail.login('alex.joubert1@gmail.com',gpassFile.read())
    gmail.select()

    ajoubertFile = open("private/mailCount/ajoubertPassword")
    ajoubert = imaplib.IMAP4_SSL('mail.gandi.net', 993)
    ajoubert.login('contact@ajoubert.com', ajoubertFile.read())
    ajoubert.select()

    val = 0;
    val = len(gmail.search(None, 'UnSeen')[1][0].split());
    val += len( ajoubert.search(None, 'UnSeen')[1][0].split() );
    if val != 0 :
        print(val)
    else :
        print("")
except:
    print("")
