#!/bin/sh

#rofi -show drun -fullscreen -monitor -1 -fg "#B0E670" -bg "#14161F" -hlfg "#14161F" -hlbg "#B0E670" -bc "#14161F" -location 0 -lines 19 -bw 0 -font "Mo    nacoB 16" -padding 280 separator-style none -a terminal urxvtc
rofi -show drun -monitor -1 -location 0 -lines 10
