#!/bin/sh

#rofi -show ssh -fullscreen -monitor -1 -fg "#B0E670" -bg "#14161F" -hlfg "#14161F" -hlbg "#B0E670" -bc "#14161F" -location 0 -lines 19 -bw 0 -font "MonacoB 16" -padding 280 separator-style none -opacity 80 -a terminal urxvtc

rofi -show ssh -monitor -1 -location 0 -lines 10
