#!/bin/bash

# Regular updates
#sudo pacman -Syu;

# Asks for password for ansible-related scripts
echo -n "Enter KeePassXC database password: "
read -s KP_PASSWORD
echo
 
# AUR updates
yay -Syu;
 
# NPM updates
if [ -x "$(command -v npm)" ];
then
  npm -g update;
fi

# GO packages
## Removed due to the change of behaviour with go modules (see [27643](https://github.com/golang/go/issues/27643))
## TODO: investigate another way to manage go global tooling

# Ruby packages
if [ -x "$(command -v gem)" ];
then
  gem update
fi
 
# VIM plugins updates
if [ -x "$(command -v /usr/bin/nvim)" ];
then
  /usr/bin/nvim --headless "+Lazy! sync" "+Lazy! update" +qa
fi
 
# TMUX plugins updates
~/.config/tmux/plugins/tpm/bin/update_plugins all

## Gnucash quotes
if [ -f "$GNUCASH_FILE" ]; then
  gnucash-cli --quotes get $GNUCASH_FILE
fi


## Remote servers update
upgradeOverAnsible.sh $KP_PASSWORD

# SDK manager update
if [ -x "$(command -v sdkmanager)" ];
then
  sdkmanager --update
fi

# PIP update
## if [ -x "$(command -v pip)" ];
## then
##   pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
## fi

## a0 upgrade
## if [ "$(ls -A /mnt/a0/boot)" ]; then
##   sudo arch-chroot /mnt/a0 pacman -Syu --noconfirm
## else
##   echo "a0 not present, skipping";
## fi

