#!/bin/bash

# Regular updates
sudo pacman -Syu;
 
# AUR updates (intentionally decoupled from pacman)
yay -Syu;
 
# NPM updates
npm -g update;
 
# VIM plugins updates
/usr/bin/vim +PlugUpgrade +PlugUpdate +qa
 
# TMUX plugins updates
~/.tmux/plugins/tpm/bin/update_plugins all

## Remote servers update
ansible-playbook $PLAYBOOKS_HOME/upgrade_all.yml

## a0 upgrade
if [ "$(ls -A /mnt/a0/boot)" ]; then
  sudo arch-chroot /mnt/a0 pacman -Syu --noconfirm
else
  echo "a0 not present, skipping";
fi

