#! /bin/sh

# kill all the bspc process first
kill -9 $(ps aux | grep bspc | sed 's/\s\+/ /g' | cut -d' ' -f2 | xargs)

sxhkd &>> /tmp/sxhkd.log &

if [[ $(hostname) == 'me110n' ]]; then
    bspc monitor DVI-D-0 -d I II III IV V
    bspc monitor HDMI-0 -d VI VII VIII IX X
else
    bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding         27

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Steam state=floating follow=on
bspc rule -a Unity state=floating
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a scratchpad sticky=on state=floating hidden=on

## Add backgrounds
sh ~/.local/scripts/randomBgAndVideo.sh &


## Add polybar
sh ~/.config/polybar/launch.sh

## Starts compton
compton &

## Starts dunst
dunst &
