#! /bin/sh

sxhkd &

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding         20 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-1 -d I II III IV V
bspc monitor eDP-1 -d VI VII VIII IX X

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a gnucash desktop=^6
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

hsetroot -center ~/.wallpaper

#panel &
lemonbuddy main &
lemonbuddy secondary &
gnucash &
