if "" == $VIM_CONFIG
  echom "$VIM_CONFIG variable is not set, skipping sourcing"
  finish
endif
source $VIM_CONFIG/config/shared/config.vim
source $VIM_CONFIG/config/shared/shortcuts_noplugin.vim
source $VIM_CONFIG/config/shared/startup.vim
"source $VIM_CONFIG/config/shared/pain.vim

if !filereadable(expand("$VIM_CONFIG/autoload/plug.vim")) 
  finish 
endif


if has('nvim')
  source $VIM_CONFIG/config/neovim/plugged.vim
  source $VIM_CONFIG/config/neovim/shortcuts.vim
  luafile $VIM_CONFIG/config/neovim/lua/nvim-lsp.lua
  luafile $VIM_CONFIG/config/neovim/lua/nvim-treesitter.lua
else
  source $VIM_CONFIG/config/vim/plugged.vim
  source $VIM_CONFIG/config/vim/shortcuts.vim
endif

