require("ui.osd")
require("ui.bar.bar")
require("ui.notifs")
require("ui.notifs_center")
require("ui.calendar")
require("ui.titlebars")
require("ui.control")
-- require("ui.lock")
require("ui.powermenu")
require("ui.launcher")

awesome.emit_signal("widgets::load_all_data")
